export enum ErrorCode {
  // Policy violations
  TOKEN_NOT_ALLOWED = 'TOKEN_NOT_ALLOWED',
  RECIPIENT_NOT_ALLOWED = 'RECIPIENT_NOT_ALLOWED',
  EXCEEDS_PER_TX_LIMIT = 'EXCEEDS_PER_TX_LIMIT',
  EXCEEDS_DAILY_LIMIT = 'EXCEEDS_DAILY_LIMIT',
  COOLDOWN_ACTIVE = 'COOLDOWN_ACTIVE',
  SWAPS_DISABLED = 'SWAPS_DISABLED',
  ROUTER_NOT_ALLOWED = 'ROUTER_NOT_ALLOWED',

  // Approval
  REQUIRES_APPROVAL = 'REQUIRES_APPROVAL',
  APPROVAL_EXPIRED = 'APPROVAL_EXPIRED',
  APPROVAL_NOT_FOUND = 'APPROVAL_NOT_FOUND',
  MAX_PENDING_APPROVALS = 'MAX_PENDING_APPROVALS',

  // Authorization
  NOT_OWNER = 'NOT_OWNER',
  NOT_AGENT = 'NOT_AGENT',
  AGENT_REVOKED = 'AGENT_REVOKED',

  // Wallet
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  WALLET_ALREADY_EXISTS = 'WALLET_ALREADY_EXISTS',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',

  // Chain
  CHAIN_NOT_SUPPORTED = 'CHAIN_NOT_SUPPORTED',
  RPC_ERROR = 'RPC_ERROR',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  BUNDLER_ERROR = 'BUNDLER_ERROR',

  // General
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  INVALID_CONFIG = 'INVALID_CONFIG',
}

export class PayClawError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly details?: Record<string, unknown>,
  ) {
    super(`[${code}] ${message}`);
    this.name = 'PayClawError';
  }
}
